// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: tx.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgCreateRoadOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Active  bool   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *MsgCreateRoadOperator) Reset() {
	*x = MsgCreateRoadOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateRoadOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateRoadOperator) ProtoMessage() {}

func (x *MsgCreateRoadOperator) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateRoadOperator.ProtoReflect.Descriptor instead.
func (*MsgCreateRoadOperator) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateRoadOperator) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateRoadOperator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgCreateRoadOperator) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgCreateRoadOperator) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type MsgCreateRoadOperatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *MsgCreateRoadOperatorResponse) Reset() {
	*x = MsgCreateRoadOperatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateRoadOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateRoadOperatorResponse) ProtoMessage() {}

func (x *MsgCreateRoadOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateRoadOperatorResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateRoadOperatorResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateRoadOperatorResponse) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type MsgUpdateRoadOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index   string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token   string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Active  bool   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *MsgUpdateRoadOperator) Reset() {
	*x = MsgUpdateRoadOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpdateRoadOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateRoadOperator) ProtoMessage() {}

func (x *MsgUpdateRoadOperator) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateRoadOperator.ProtoReflect.Descriptor instead.
func (*MsgUpdateRoadOperator) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateRoadOperator) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgUpdateRoadOperator) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *MsgUpdateRoadOperator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgUpdateRoadOperator) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgUpdateRoadOperator) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type MsgUpdateRoadOperatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgUpdateRoadOperatorResponse) Reset() {
	*x = MsgUpdateRoadOperatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpdateRoadOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateRoadOperatorResponse) ProtoMessage() {}

func (x *MsgUpdateRoadOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateRoadOperatorResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateRoadOperatorResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

type MsgDeleteRoadOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index   string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *MsgDeleteRoadOperator) Reset() {
	*x = MsgDeleteRoadOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDeleteRoadOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDeleteRoadOperator) ProtoMessage() {}

func (x *MsgDeleteRoadOperator) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDeleteRoadOperator.ProtoReflect.Descriptor instead.
func (*MsgDeleteRoadOperator) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgDeleteRoadOperator) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgDeleteRoadOperator) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type MsgDeleteRoadOperatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgDeleteRoadOperatorResponse) Reset() {
	*x = MsgDeleteRoadOperatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDeleteRoadOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDeleteRoadOperatorResponse) ProtoMessage() {}

func (x *MsgDeleteRoadOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDeleteRoadOperatorResponse.ProtoReflect.Descriptor instead.
func (*MsgDeleteRoadOperatorResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

// MsgCreateUserVault defines a message for creating a UserVault
type MsgCreateUserVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                     // The creator of the vault, acting as the owner
	RoadOperatorIndex string `protobuf:"bytes,2,opt,name=roadOperatorIndex,proto3" json:"roadOperatorIndex,omitempty"` // The index of the associated road operator
	Token             string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                         // The token denomination
	Balance           uint64 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`                    // The initial balance of the token
}

func (x *MsgCreateUserVault) Reset() {
	*x = MsgCreateUserVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateUserVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateUserVault) ProtoMessage() {}

func (x *MsgCreateUserVault) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateUserVault.ProtoReflect.Descriptor instead.
func (*MsgCreateUserVault) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgCreateUserVault) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateUserVault) GetRoadOperatorIndex() string {
	if x != nil {
		return x.RoadOperatorIndex
	}
	return ""
}

func (x *MsgCreateUserVault) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgCreateUserVault) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type MsgCreateUserVaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgCreateUserVaultResponse) Reset() {
	*x = MsgCreateUserVaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateUserVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateUserVaultResponse) ProtoMessage() {}

func (x *MsgCreateUserVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateUserVaultResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateUserVaultResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

// MsgUpdateUserVault defines a message for updating a UserVault's balance
type MsgUpdateUserVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                     // The creator of the vault, acting as the owner
	RoadOperatorIndex string `protobuf:"bytes,2,opt,name=roadOperatorIndex,proto3" json:"roadOperatorIndex,omitempty"` // The index of the associated road operator
	Token             string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                         // The token denomination
	Balance           uint64 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`                    // The new balance of the token
}

func (x *MsgUpdateUserVault) Reset() {
	*x = MsgUpdateUserVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpdateUserVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateUserVault) ProtoMessage() {}

func (x *MsgUpdateUserVault) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateUserVault.ProtoReflect.Descriptor instead.
func (*MsgUpdateUserVault) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgUpdateUserVault) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgUpdateUserVault) GetRoadOperatorIndex() string {
	if x != nil {
		return x.RoadOperatorIndex
	}
	return ""
}

func (x *MsgUpdateUserVault) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgUpdateUserVault) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type MsgUpdateUserVaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgUpdateUserVaultResponse) Reset() {
	*x = MsgUpdateUserVaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpdateUserVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateUserVaultResponse) ProtoMessage() {}

func (x *MsgUpdateUserVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateUserVaultResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateUserVaultResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

type MsgDeleteUserVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                     // The creator of the vault, acting as the owner
	RoadOperatorIndex string `protobuf:"bytes,2,opt,name=roadOperatorIndex,proto3" json:"roadOperatorIndex,omitempty"` // The index of the associated road operator
	Token             string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                         // The token denomination
}

func (x *MsgDeleteUserVault) Reset() {
	*x = MsgDeleteUserVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDeleteUserVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDeleteUserVault) ProtoMessage() {}

func (x *MsgDeleteUserVault) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDeleteUserVault.ProtoReflect.Descriptor instead.
func (*MsgDeleteUserVault) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgDeleteUserVault) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgDeleteUserVault) GetRoadOperatorIndex() string {
	if x != nil {
		return x.RoadOperatorIndex
	}
	return ""
}

func (x *MsgDeleteUserVault) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MsgDeleteUserVaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgDeleteUserVaultResponse) Reset() {
	*x = MsgDeleteUserVaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDeleteUserVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDeleteUserVaultResponse) ProtoMessage() {}

func (x *MsgDeleteUserVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDeleteUserVaultResponse.ProtoReflect.Descriptor instead.
func (*MsgDeleteUserVaultResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

var File_tx_proto protoreflect.FileDescriptor

var file_tx_proto_rawDesc = []byte{
	0x0a, 0x08, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x62, 0x39, 0x6c, 0x61,
	0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72,
	0x6f, 0x61, 0x64, 0x22, 0x73, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x35, 0x0a, 0x1d, 0x4d, 0x73, 0x67, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x89, 0x01, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61,
	0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x4d,
	0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x15,
	0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x1f, 0x0a, 0x1d, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x6f, 0x61, 0x64, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x72, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x72, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x72, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x2c, 0x0a, 0x11, 0x72, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x6f, 0x61,
	0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1c, 0x0a, 0x1a, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xde, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x7c, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x2e, 0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61,
	0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x1a, 0x36, 0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61,
	0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2e,
	0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e,
	0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x36,
	0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e,
	0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7c, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x2e, 0x62,
	0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f,
	0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x36, 0x2e, 0x62,
	0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f,
	0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x61, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e,
	0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61,
	0x64, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x1a, 0x33, 0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c,
	0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d,
	0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x0f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x2e, 0x62,
	0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f,
	0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x1a, 0x33, 0x2e, 0x62, 0x39, 0x6c, 0x61,
	0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72,
	0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f,
	0x61, 0x64, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x1a, 0x33,
	0x2e, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e,
	0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x39, 0x6c, 0x61, 0x62, 0x2f, 0x74, 0x6f, 0x6c, 0x6c, 0x2d, 0x72, 0x6f, 0x61,
	0x64, 0x2f, 0x78, 0x2f, 0x74, 0x6f, 0x6c, 0x6c, 0x72, 0x6f, 0x61, 0x64, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData = file_tx_proto_rawDesc
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_tx_proto_rawDescData)
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tx_proto_goTypes = []interface{}{
	(*MsgCreateRoadOperator)(nil),         // 0: b9lab.tollroad.tollroad.MsgCreateRoadOperator
	(*MsgCreateRoadOperatorResponse)(nil), // 1: b9lab.tollroad.tollroad.MsgCreateRoadOperatorResponse
	(*MsgUpdateRoadOperator)(nil),         // 2: b9lab.tollroad.tollroad.MsgUpdateRoadOperator
	(*MsgUpdateRoadOperatorResponse)(nil), // 3: b9lab.tollroad.tollroad.MsgUpdateRoadOperatorResponse
	(*MsgDeleteRoadOperator)(nil),         // 4: b9lab.tollroad.tollroad.MsgDeleteRoadOperator
	(*MsgDeleteRoadOperatorResponse)(nil), // 5: b9lab.tollroad.tollroad.MsgDeleteRoadOperatorResponse
	(*MsgCreateUserVault)(nil),            // 6: b9lab.tollroad.tollroad.MsgCreateUserVault
	(*MsgCreateUserVaultResponse)(nil),    // 7: b9lab.tollroad.tollroad.MsgCreateUserVaultResponse
	(*MsgUpdateUserVault)(nil),            // 8: b9lab.tollroad.tollroad.MsgUpdateUserVault
	(*MsgUpdateUserVaultResponse)(nil),    // 9: b9lab.tollroad.tollroad.MsgUpdateUserVaultResponse
	(*MsgDeleteUserVault)(nil),            // 10: b9lab.tollroad.tollroad.MsgDeleteUserVault
	(*MsgDeleteUserVaultResponse)(nil),    // 11: b9lab.tollroad.tollroad.MsgDeleteUserVaultResponse
}
var file_tx_proto_depIdxs = []int32{
	0,  // 0: b9lab.tollroad.tollroad.Msg.CreateRoadOperator:input_type -> b9lab.tollroad.tollroad.MsgCreateRoadOperator
	2,  // 1: b9lab.tollroad.tollroad.Msg.UpdateRoadOperator:input_type -> b9lab.tollroad.tollroad.MsgUpdateRoadOperator
	4,  // 2: b9lab.tollroad.tollroad.Msg.DeleteRoadOperator:input_type -> b9lab.tollroad.tollroad.MsgDeleteRoadOperator
	6,  // 3: b9lab.tollroad.tollroad.Msg.CreateUserVault:input_type -> b9lab.tollroad.tollroad.MsgCreateUserVault
	8,  // 4: b9lab.tollroad.tollroad.Msg.UpdateUserVault:input_type -> b9lab.tollroad.tollroad.MsgUpdateUserVault
	10, // 5: b9lab.tollroad.tollroad.Msg.DeleteUserVault:input_type -> b9lab.tollroad.tollroad.MsgDeleteUserVault
	1,  // 6: b9lab.tollroad.tollroad.Msg.CreateRoadOperator:output_type -> b9lab.tollroad.tollroad.MsgCreateRoadOperatorResponse
	3,  // 7: b9lab.tollroad.tollroad.Msg.UpdateRoadOperator:output_type -> b9lab.tollroad.tollroad.MsgUpdateRoadOperatorResponse
	5,  // 8: b9lab.tollroad.tollroad.Msg.DeleteRoadOperator:output_type -> b9lab.tollroad.tollroad.MsgDeleteRoadOperatorResponse
	7,  // 9: b9lab.tollroad.tollroad.Msg.CreateUserVault:output_type -> b9lab.tollroad.tollroad.MsgCreateUserVaultResponse
	9,  // 10: b9lab.tollroad.tollroad.Msg.UpdateUserVault:output_type -> b9lab.tollroad.tollroad.MsgUpdateUserVaultResponse
	11, // 11: b9lab.tollroad.tollroad.Msg.DeleteUserVault:output_type -> b9lab.tollroad.tollroad.MsgDeleteUserVaultResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateRoadOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateRoadOperatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpdateRoadOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpdateRoadOperatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDeleteRoadOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDeleteRoadOperatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateUserVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateUserVaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpdateUserVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpdateUserVaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDeleteUserVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDeleteUserVaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_rawDesc = nil
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
